project:
  type: website

website:
  title: "Lisa DeBruine"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - cv.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    fontsize: 16px
    css: styles.css
    toc: true



